### ISSUE TITLE
Some more device stats

### ISSUE THREAD

**Issue by fakemanhk** [cyyself/wg-bench#12]
Sorry I am a new user to GitHub so don't know how to create the PR (tried but not successful, might learn about it later)

Below are some recently tested devices:

RPi 3B - BCM2837  
5.15.137 OpenWrt 23.05.2  
517Mbps

RPi B Rev 2 - BCM2835
5.15.137 OpenWrt 23.05.2  
16.1Mbps

NanoPi R2S (RK3328)  
5.15.137 OpenWrt 23.05.2  
234Mbps

Linksys WRT3200ACM - Marvell 88F6820 (1.8GHz)  
5.15.137 OpenWrt 23.05.2  
426Mbps

Linksys WRT1900ACv2 - Marvell 88F6820 (1.3GHz)  
5.15.137 OpenWrt 23.05.2  
361Mbps

**Comment by cyyself** [comment]
Thanks, I will add it to the test result.

**Comment by cyyself** [comment]
Thanks for [your post on the OpenWRT forum](https://forum.openwrt.org/t/a-wireguard-comparison-db/187586). I found more results there.

**Comment by fakemanhk** [comment]
Now there are a lot more results there.
