### ISSUE TITLE
More real workloads

### ISSUE THREAD

**Issue by dtaht** [cyyself/wg-bench#38]
I occasionally try to point out that pure throughput benchmarks are not really how the internet is used.  You might have one full rate flow, but most of time it is lots of little flows, that never get out of slow start. This is especially true for most vpn traffic that isn´t taking bittorrent across it. 

Flent´s rrul test vs wireguard is interesting. It has been relentlessly optimized for throughput and not latency. Also crusaders staggered start test is revealing.

**Comment by cyyself** [comment]
I agree. For many little flow cases, the host CPU (we use the router itself now) and its NIC driver will likely be a bottleneck. So, for now, I do not know a simple way to benchmark something like packet forward rate. I would appreciate it if you could provide a better benchmark solution.
