### ISSUE TITLE
Strange Performance on Raspbeery Pi 4

### ISSUE THREAD

**Issue by cyyself** [cyyself/wg-bench#5]
Based on the results, even the 2GHz Quad-Core A53 on TP-Link XDR 6088 can achieve 818 Mbits/sec. I doubt the Raspberry Pi 4's result of only 394 Mbits/sec is accurate as it has Quad-Core A72 @ 1.5GHz. Then, I switched back to the archlinuxarm-based PiKVM distro which my Raspberry PI 4 usually works on with armv7l kernel rather than aarch64 on Raspberry Pi OS, and ran the benchmark. Then, the result made me astonished.

```markdown
| Device / CPU                   | OS / Kernel / iperf Param  | Speed          |
| Raspberry Pi 4 / BCM2711*      | Debian bookworm / 6.1.63   | 394 Mbits/sec  |
| Raspberry Pi 4 / BCM2711*      | archlinux / 6.1.61(armv7l) | 665 Mbits/sec  |
```

Using armv7l Kernel we will get about 69% faster, WHY?

I searched on the web and found a thread that has the same confusion as me but on AES rather than chacha20 used by wg[1]. It might be the chacha20 implementation in the kernel is not optimized in aarch64. I want to leave the issue here to record any further investigation of this performance issue.

[1] https://forums.raspberrypi.com/viewtopic.php?t=317075

**Comment by cyyself** [comment]
Update: After directly flashing my rpi4 with OpenWRT 23.05.2 with Linux v5.15.137 compiled by OpenWRT, I got 1.01 Gbit/sec!

```markdown
| Raspberry Pi 4 / BCM2711*      | OpenWRT 23.05.2 / 5.15.137 | 1.01 Gbits/sec |
```

**Comment by cyyself** [comment]
One interesting finding: Use `CONFIG_PREEMPT_NONE` instead of `CONFIG_PREEMPT` we can reach ~700Mbps in 6.1.y Kernel. `CONFIG_PREEMPT_NONE` is set by default in OpenWRT Kernel.

```console
Connecting to host 169.254.200.2, port 5201
[  5] local 169.254.200.1 port 47296 connected to 169.254.200.2 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  78.2 MBytes   656 Mbits/sec    0    402 KBytes       
[  5]   1.00-2.00   sec  80.2 MBytes   672 Mbits/sec    0    441 KBytes       
[  5]   2.00-3.00   sec  79.6 MBytes   668 Mbits/sec    0    441 KBytes       
[  5]   3.00-4.00   sec  80.3 MBytes   674 Mbits/sec    0    441 KBytes       
[  5]   4.00-5.00   sec  80.8 MBytes   678 Mbits/sec    0    441 KBytes       
[  5]   5.00-6.00   sec  81.0 MBytes   679 Mbits/sec    0    441 KBytes       
[  5]   6.00-7.00   sec  79.5 MBytes   667 Mbits/sec    0    441 KBytes       
[  5]   7.00-8.00   sec  80.1 MBytes   672 Mbits/sec    0    441 KBytes       
[  5]   8.00-9.00   sec  80.1 MBytes   672 Mbits/sec    0    441 KBytes       
[  5]   9.00-10.00  sec  79.7 MBytes   668 Mbits/sec    0    441 KBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec   799 MBytes   671 Mbits/sec    0             sender
[  5]   0.00-10.00  sec   798 MBytes   669 Mbits/sec                  receiver

iperf Done.
```

**Comment by cyyself** [comment]
Another interesting finding: Turn off `CONFIG_FTRACE` together with `CONFIG_PREEMPT_NONE` we can reach ~1.1Gbps on bcm2711_defconfig with [rpi-6.1.y](https://github.com/raspberrypi/linux/tree/rpi-6.1.y).

```console
Connecting to host 169.254.200.2, port 5201
[  5] local 169.254.200.1 port 37182 connected to 169.254.200.2 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   135 MBytes  1.13 Gbits/sec    0    818 KBytes       
[  5]   1.00-2.00   sec   130 MBytes  1.09 Gbits/sec    0    860 KBytes       
[  5]   2.00-3.00   sec   126 MBytes  1.05 Gbits/sec    0    975 KBytes       
[  5]   3.00-4.00   sec   130 MBytes  1.09 Gbits/sec    0   1022 KBytes       
[  5]   4.00-5.00   sec   130 MBytes  1.09 Gbits/sec    0   1.07 MBytes       
[  5]   5.00-6.00   sec   132 MBytes  1.11 Gbits/sec    0   1.07 MBytes       
[  5]   6.00-7.00   sec   132 MBytes  1.11 Gbits/sec    0   1.14 MBytes       
[  5]   7.00-8.00   sec   132 MBytes  1.11 Gbits/sec    0   1.26 MBytes       
[  5]   8.00-9.00   sec   129 MBytes  1.08 Gbits/sec    0   1.26 MBytes       
[  5]   9.00-10.01  sec   130 MBytes  1.08 Gbits/sec    0   1.48 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.01  sec  1.28 GBytes  1.09 Gbits/sec    0             sender
[  5]   0.00-10.01  sec  1.27 GBytes  1.09 Gbits/sec                  receiver

iperf Done.
```

**Comment by cyyself** [comment]
Yet another interesting finding: turn off `CONFIG_IRQSOFF_TRACER` along with `CONFIG_PREEMPT_NONE` can also reach ~1.1Gbps.

**Comment by fakemanhk** [comment]
In my RPi 4B, using OpenWrt 23.05.2 (64bit), the tested result was 881Mbps.

**Comment by fakemanhk** [comment]
BTW I believe 32bit VS 64bit should show some difference, probably we should indicate this?

**Comment by cyyself** [comment]
> BTW I believe 32bit VS 64bit should show some difference, probably we should indicate this?

For an out-of-order CPU, 32bit vs 64bit shows same performance is normal, and chacha20 and poly1305 also uses SIMD i.e. arm neon to calculate, if uarch implementation does not provide wide enough simd processing, we will get the same performance on whatever 32/64 bit.
